version: '3'
services:
  ai4prod_ui_container_dev:
    image: ai4prod_ui:base #Specifiy The image
    command: ["/bin/bash"]
    shm_size: '8gb'
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 80:80
      - 4040:4040
    volumes:
      - /media/dati/Develop/ai4prod_repo/Coding/Ai4prodGuiData/Experiment:/home/Develop/Experiment
      - /media/dati/Develop/ai4prod_repo/Coding/Ai4prodGuiData/Dataset:/home/Develop/Dataset
    