FROM ai_training

RUN pip3 install flask==2.2.4 
RUN pip3 install flask_sqlalchemy==3.0.0
RUN pip3 install GitPython==3.1.32
RUN pip3 install plot plotly-express
RUN pip3 install atlassian-python-api==3.40.0
RUN pip3 install turbo_flask==0.8.4 
